import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    FileText, Download, Eye, Target, Calendar,
    ArrowLeft, Shield, Bug, AlertTriangle, ChevronRight,
    Loader, Clock, CheckCircle, Hash
} from 'lucide-react';
import { listScans, listVulnerabilities, getScanReport } from '../../services/offensiveService';

/* ──────────────────────────────────────────────────────
   Helpers
────────────────────────────────────────────────────── */
const SEV_STYLE = {
    critical: { ring: 'border-red-500/60', bg: 'bg-red-500/10', text: 'text-red-400', badge: 'bg-red-500 text-white' },
    high: { ring: 'border-orange-500/60', bg: 'bg-orange-500/10', text: 'text-orange-400', badge: 'bg-orange-500 text-white' },
    medium: { ring: 'border-yellow-500/60', bg: 'bg-yellow-500/10', text: 'text-yellow-400', badge: 'bg-yellow-500/30 text-yellow-300' },
    low: { ring: 'border-green-500/60', bg: 'bg-green-500/10', text: 'text-green-400', badge: 'bg-green-500/30 text-green-300' },
};

const SevBadge = ({ s }) => {
    const c = SEV_STYLE[s?.toLowerCase()] ?? SEV_STYLE.low;
    return <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded ${c.badge}`}>{s ?? 'info'}</span>;
};

const fmtDate = (d) => d ? new Date(d).toLocaleDateString(undefined, { dateStyle: 'medium' }) : '—';

/* ──────────────────────────────────────────────────────
   Markdown → styled HTML (simple renderer, no library needed)
────────────────────────────────────────────────────── */
const MarkdownReport = ({ md }) => {
    if (!md) return (
        <div className="flex flex-col items-center justify-center py-24 text-gray-600">
            <FileText size={40} className="mb-3 opacity-40" />
            <p className="text-sm italic">No report generated by Strix for this scan.</p>
            <p className="text-xs mt-1 opacity-60">The agent must call <code className="font-mono">finish_scan</code> to produce a report.</p>
        </div>
    );

    // Simple line-based rendering; good enough for Strix markdown
    const lines = md.split('\n');
    const elements = [];
    let i = 0;

    while (i < lines.length) {
        const line = lines[i];
        if (line.startsWith('# ')) {
            elements.push(<h1 key={i} className="text-2xl font-bold text-white mt-6 mb-3 pb-2 border-b border-gray-700">{line.slice(2)}</h1>);
        } else if (line.startsWith('## ')) {
            elements.push(<h2 key={i} className="text-lg font-bold text-white mt-5 mb-2">{line.slice(3)}</h2>);
        } else if (line.startsWith('### ')) {
            elements.push(<h3 key={i} className="text-base font-semibold text-gray-200 mt-4 mb-1">{line.slice(4)}</h3>);
        } else if (line.startsWith('**') && line.endsWith('**')) {
            elements.push(<p key={i} className="font-bold text-gray-200 my-1">{line.slice(2, -2)}</p>);
        } else if (line.startsWith('- ') || line.startsWith('* ')) {
            elements.push(
                <li key={i} className="ml-5 text-gray-300 text-sm leading-relaxed list-disc">
                    {line.slice(2)}
                </li>
            );
        } else if (line.startsWith('```')) {
            // collect code block
            const lang = line.slice(3).trim();
            const codeLines = [];
            i++;
            while (i < lines.length && !lines[i].startsWith('```')) {
                codeLines.push(lines[i]);
                i++;
            }
            elements.push(
                <pre key={i} className="bg-gray-900 border border-gray-700 rounded-lg p-4 overflow-x-auto text-xs font-mono text-green-300 my-3 leading-relaxed">
                    {codeLines.join('\n')}
                </pre>
            );
        } else if (line.trim() === '') {
            elements.push(<div key={i} className="h-2" />);
        } else {
            // Inline bold/formatting
            const html = line
                .replace(/\*\*(.*?)\*\*/g, '<strong class="text-white">$1</strong>')
                .replace(/`(.*?)`/g, '<code class="bg-gray-800 text-green-300 px-1 rounded text-xs font-mono">$1</code>');
            elements.push(
                <p key={i} className="text-gray-300 text-sm leading-relaxed my-1"
                    dangerouslySetInnerHTML={{ __html: html }} />
            );
        }
        i++;
    }

    return <div className="font-sans text-gray-300">{elements}</div>;
};

/* ──────────────────────────────────────────────────────
   Main Page
────────────────────────────────────────────────────── */
const ReportsPage = () => {
    const [scans, setScans] = useState([]);
    const [selectedScan, setSelectedScan] = useState(null);
    const [report, setReport] = useState(null);          // { final_report_md, vulns, ... }
    const [scanVulns, setScanVulns] = useState([]);
    const [loading, setLoading] = useState(true);
    const [loadingReport, setLoadingReport] = useState(false);
    const [activeTab, setActiveTab] = useState('report'); // 'report' | 'vulns'

    useEffect(() => { loadScans(); }, []);

    const loadScans = async () => {
        try {
            const data = await listScans();
            // Show all scans — the report endpoint recovers reports even for
            // scans that ended as 'running'/'stopped' if finish_scan was called.
            setScans(data);
        } catch (e) {
            console.error(e);
        } finally {
            setLoading(false);
        }
    };

    const openScan = async (scan) => {
        setSelectedScan(scan);
        setActiveTab('report');
        setLoadingReport(true);
        try {
            const [rep, vulns] = await Promise.all([
                getScanReport(scan.id),
                listVulnerabilities({ scan_id: scan.id }),
            ]);
            setReport(rep);
            setScanVulns(vulns);
        } catch (e) {
            console.error(e);
        } finally {
            setLoadingReport(false);
        }
    };

    const downloadReport = () => {
        if (!report?.final_report_md) return;
        const blob = new Blob([report.final_report_md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `pentest-report-${selectedScan.target.replace(/[^a-z0-9]/gi, '-')}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    if (loading) return (
        <div className="flex items-center justify-center h-64">
            <Loader size={28} className="text-gray-600 animate-spin" />
        </div>
    );

    return (
        <div className="min-h-screen bg-black p-6">
            <AnimatePresence mode="wait">
                {!selectedScan ? (
                    /* ── Scan List ── */
                    <motion.div key="list" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
                        {/* Header */}
                        <div className="flex items-center gap-3 mb-8">
                            <div className="p-3 bg-gray-800/60 rounded-xl border border-gray-700/50">
                                <FileText size={28} className="text-gray-300" />
                            </div>
                            <div>
                                <h1 className="text-3xl font-bold text-white">Scan Reports</h1>
                                <p className="text-gray-500 text-sm mt-0.5">{scans.length} scan{scans.length !== 1 ? 's' : ''}</p>
                            </div>
                        </div>

                        {scans.length === 0 ? (
                            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-16 text-center">
                                <FileText size={44} className="text-gray-700 mx-auto mb-4" />
                                <p className="text-gray-500">No scans yet</p>
                                <p className="text-gray-700 text-sm mt-1">Run a scan from the Offensive Dashboard to generate reports.</p>
                            </div>
                        ) : (
                            <div className="space-y-3">
                                {scans.map((scan, idx) => (
                                    <motion.div
                                        key={scan.id}
                                        initial={{ opacity: 0, y: 8 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ delay: idx * 0.04 }}
                                        onClick={() => openScan(scan)}
                                        className="bg-[#0a0a0a] border border-gray-800 hover:border-gray-600 rounded-xl p-5 cursor-pointer transition-all group flex items-center gap-5"
                                    >
                                        {/* Icon */}
                                        <div className="p-3 bg-gray-800 rounded-lg shrink-0 group-hover:bg-gray-700 transition-colors">
                                            <Target size={20} className="text-gray-400" />
                                        </div>

                                        {/* Info */}
                                        <div className="flex-1 min-w-0">
                                            <div className="flex items-center gap-2">
                                                <span className="font-semibold text-white truncate">{scan.target}</span>
                                                <ScanStatusBadge status={scan.status} />
                                            </div>
                                            <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
                                                <span className="flex items-center gap-1"><Clock size={11} />{fmtDate(scan.completed_at || scan.started_at)}</span>
                                                <span className="flex items-center gap-1"><Hash size={11} />{scan.methodology}</span>
                                            </div>
                                        </div>

                                        {/* Severity counts */}
                                        <div className="flex items-center gap-4 shrink-0">
                                            <SevCount label="Critical" count={scan.critical_count} color="text-red-400" />
                                            <SevCount label="High" count={scan.high_count} color="text-orange-400" />
                                            <SevCount label="Medium" count={scan.medium_count} color="text-yellow-400" />
                                            <SevCount label="Low" count={scan.low_count} color="text-green-400" />
                                        </div>

                                        {/* Arrow */}
                                        <ChevronRight size={18} className="text-gray-600 group-hover:text-gray-400 transition-colors shrink-0" />
                                    </motion.div>
                                ))}
                            </div>
                        )}
                    </motion.div>
                ) : (
                    /* ── Report Detail ── */
                    <motion.div key="detail" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0 }}>
                        {/* Back + header */}
                        <div className="flex items-start justify-between mb-6">
                            <div className="flex items-center gap-3">
                                <button
                                    onClick={() => { setSelectedScan(null); setReport(null); setScanVulns([]); }}
                                    className="flex items-center gap-2 text-gray-500 hover:text-white text-sm transition-colors"
                                >
                                    <ArrowLeft size={16} /> Back to Reports
                                </button>
                            </div>
                            {report?.final_report_md && (
                                <button
                                    onClick={downloadReport}
                                    className="flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 text-white rounded-lg text-sm transition-colors border border-gray-700"
                                >
                                    <Download size={14} /> Download .md
                                </button>
                            )}
                        </div>

                        {/* Target banner */}
                        <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-5 mb-5 flex items-center gap-4">
                            <div className="p-3 bg-gray-800 rounded-lg">
                                <Shield size={24} className="text-green-400" />
                            </div>
                            <div className="flex-1">
                                <h1 className="text-2xl font-bold text-white">{selectedScan.target}</h1>
                                <p className="text-gray-500 text-sm mt-0.5">
                                    {selectedScan.methodology} · Completed {fmtDate(selectedScan.completed_at)}
                                </p>
                            </div>
                            {/* Summary counts */}
                            <div className="flex gap-5">
                                {[
                                    { label: 'Critical', v: selectedScan.critical_count, c: 'text-red-400' },
                                    { label: 'High', v: selectedScan.high_count, c: 'text-orange-400' },
                                    { label: 'Medium', v: selectedScan.medium_count, c: 'text-yellow-400' },
                                    { label: 'Low', v: selectedScan.low_count, c: 'text-green-400' },
                                ].map(({ label, v, c }) => (
                                    <div key={label} className="text-center">
                                        <div className={`text-2xl font-bold ${c}`}>{v}</div>
                                        <div className="text-[10px] text-gray-600 uppercase tracking-wider">{label}</div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Tabs */}
                        <div className="flex gap-1 mb-5 bg-gray-900/50 p-1 rounded-lg w-fit border border-gray-800">
                            {[
                                { id: 'report', label: 'Pentest Report', icon: <FileText size={14} /> },
                                { id: 'vulns', label: `Vulnerabilities (${scanVulns.length})`, icon: <Bug size={14} /> },
                            ].map(tab => (
                                <button
                                    key={tab.id}
                                    onClick={() => setActiveTab(tab.id)}
                                    className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === tab.id
                                        ? 'bg-white/10 text-white'
                                        : 'text-gray-500 hover:text-gray-300'}`}
                                >
                                    {tab.icon} {tab.label}
                                </button>
                            ))}
                        </div>

                        {/* Tab content */}
                        {loadingReport ? (
                            <div className="flex items-center justify-center py-24">
                                <Loader size={28} className="text-gray-600 animate-spin" />
                            </div>
                        ) : activeTab === 'report' ? (
                            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-8">
                                <MarkdownReport md={report?.final_report_md} />
                            </div>
                        ) : (
                            /* Vulns tab */
                            <div className="space-y-3">
                                {scanVulns.length === 0 ? (
                                    <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-12 text-center">
                                        <CheckCircle size={36} className="text-green-600 mx-auto mb-3" />
                                        <p className="text-gray-400">No vulnerabilities recorded for this scan.</p>
                                    </div>
                                ) : (
                                    scanVulns.map((v, i) => (
                                        <VulnCard key={v.id} vuln={v} idx={i} />
                                    ))
                                )}
                            </div>
                        )}
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

/* ──────────────────────────────────────────────────────
   Small components
────────────────────────────────────────────────────── */
const ScanStatusBadge = ({ status }) => {
    const cls = {
        completed: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
        running: 'bg-green-500/20 text-green-400 border-green-500/30',
        stopped: 'bg-gray-600/20 text-gray-400 border-gray-600/30',
        failed: 'bg-red-500/20 text-red-400 border-red-500/30',
        pending: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
    }[status] ?? 'bg-gray-700/20 text-gray-500 border-gray-700/30';
    return <span className={`shrink-0 text-[9px] font-bold uppercase px-1.5 py-0.5 rounded border ${cls}`}>{status}</span>;
};

const SevCount = ({ label, count, color }) => (
    <div className="text-center min-w-[36px]">
        <div className={`text-lg font-bold ${color}`}>{count}</div>
        <div className="text-[9px] text-gray-600 uppercase tracking-wider">{label}</div>
    </div>
);

const VulnCard = ({ vuln, idx }) => {
    const [expanded, setExpanded] = useState(false);
    const s = (vuln.severity ?? 'low').toLowerCase();
    const st = SEV_STYLE[s] ?? SEV_STYLE.low;

    return (
        <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.04 }}
            className={`border rounded-xl overflow-hidden transition-all ${st.ring} ${st.bg}`}
        >
            <button
                className="w-full px-5 py-4 flex items-center gap-3 text-left"
                onClick={() => setExpanded(e => !e)}
            >
                <SevBadge s={s} />
                <span className="flex-1 font-semibold text-white text-sm">{vuln.title}</span>
                <span className="text-gray-600 text-xs">{fmtDate(vuln.found_at)}</span>
                <ChevronRight size={15} className={`text-gray-500 transition-transform ${expanded ? 'rotate-90' : ''}`} />
            </button>
            <AnimatePresence>
                {expanded && (
                    <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden"
                    >
                        <div className="px-5 pb-4 border-t border-white/5 pt-3">
                            <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{vuln.content}</p>
                            {vuln.poc && (
                                <div className="mt-3">
                                    <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">PoC / Report ID</p>
                                    <code className="text-xs font-mono text-green-400 bg-black/30 px-2 py-1 rounded">{vuln.poc}</code>
                                </div>
                            )}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </motion.div>
    );
};

export default ReportsPage;
