"""create_licenses_table

Revision ID: 67217f7b8866
Revises: 43e80fb1ef8e
Create Date: 2025-12-08 01:00:41.002108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67217f7b8866'
down_revision: Union[str, Sequence[str], None] = '43e80fb1ef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_licenses_key'), 'licenses', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_key'), table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###
